package com.hamrobill.utility

const val FRAGMENT_CONTAINER_WIDTH_LIMIT = 2300
const val DIALOG_WIDTH_LIMIT = 2000
const val RECYCLER_VIEW_WIDTH_LIMIT = 2500
const val DIALOG_WIDTH_RATIO_BIG = 0.65
const val DIALOG_WIDTH_RATIO_SMALL = 0.80

const val PROGRESS_DIALOG_WIDTH_RATIO_BIG = 0.30
const val PROGRESS_DIALOG_WIDTH_RATIO_SMALL = 0.50